// Generated by OrchestKit Claude Plugin
// Created: 2026-09-01

import { test } from "node:test";
import assert from "node:assert/strict";
import { idempotencyCheck } from "./idempotency.js";
import type { IntentDefinition } from "../systems/definition.js";

const guarded: IntentDefinition = {
  name: "create_ticket",
  description: "",
  params: [],
  mutating: true,
  idempotency: { kind: "textVisible", value: "{subject}" },
};

test("returns the existence check when a guarded intent is about to write", () => {
  assert.deepEqual(idempotencyCheck(guarded, true), { kind: "textVisible", value: "{subject}" });
});

test("returns null when the intent will not write", () => {
  assert.equal(idempotencyCheck(guarded, false), null);
});

test("returns null when the intent declares no idempotency guard", () => {
  const plain: IntentDefinition = { name: "x", description: "", params: [], mutating: true };
  assert.equal(idempotencyCheck(plain, true), null);
});
