// Generated by OrchestKit Claude Plugin
// Created: 2026-09-01

import type { Verify } from "../types.js";
import type { IntentDefinition } from "../systems/definition.js";

export function idempotencyCheck(definition: IntentDefinition, willWrite: boolean): Verify | null {
  if (!willWrite) return null;
  return definition.idempotency ?? null;
}
