// Generated by OrchestKit Claude Plugin
// Created: 2026-08-31

import type { Locator, RobustTarget, Step } from "../types.js";
import type { SystemDefinition } from "./definition.js";

const target = (primary: Locator, ...fallbacks: Locator[]): RobustTarget => ({ primary, fallbacks });
const role = (roleName: string, value: string): Locator => ({ strategy: "role", role: roleName, value });
const css = (value: string): Locator => ({ strategy: "css", value });
const placeholder = (value: string): Locator => ({ strategy: "placeholder", value });

const BASE = "https://opensource-demo.orangehrmlive.com/web/index.php";

export const ORANGEHRM_DEMO_CREDENTIALS: Record<string, string> = {
  username: "Admin",
  password: "admin123",
};

export const orangehrm: SystemDefinition = {
  id: "orangehrm-demo",
  baseUrl: `${BASE}/auth/login`,
  auth: {
    credentialKeys: ["username", "password"],
    loginSteps: [
      { action: "type", target: target(css('input[name="username"]'), placeholder("Username")), value: "{secret:username}" },
      { action: "type", target: target(css('input[name="password"]'), placeholder("Password")), value: "{secret:password}" },
      {
        action: "click",
        target: target(role("button", "Login"), css('button[type="submit"]')),
        verify: { kind: "urlIncludes", value: "dashboard" },
      },
    ],
  },
  intents: [
    {
      name: "list_employees",
      description: "Read the employee directory (PIM employee list).",
      params: [],
      mutating: false,
      build: (): Step[] => [
        { action: "navigate", value: `${BASE}/pim/viewEmployeeList` },
        { action: "waitFor", target: target(css(".oxd-table-card")) },
        { action: "extract", target: target(css(".oxd-table-card")), value: "employees" },
      ],
    },
  ],
};
